sudo: false
services: mongodb
env:
  global:
    - NODE_ENV=test
language: node_js
node_js:
  - '10.15.1'
cache:
  directories:
    - node_modules
branches:
  only:
    - develop
install:
  - npm install
before_script:
  - mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
script:
  - npm run test